# Generated by Django 6.0.2 on 2026-02-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_title_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='board_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
