# Generated by Django 6.0.2 on 2026-02-07 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('completed', 'Completed'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('tagged', 'Tagged'), ('untagged', 'Untagged')], max_length=20)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
                ('target_title', models.CharField(max_length=200)),
                ('delta', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='activity_ac_target__16e969_idx'), models.Index(fields=['actor', '-created_at'], name='activity_ac_actor_i_3a6bb7_idx')],
            },
        ),
    ]
