# Generated by Django 6.0.2 on 2026-02-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('completed', 'Completed'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('tagged', 'Tagged'), ('untagged', 'Untagged'), ('rearranged', 'Rearranged'), ('interacted', 'Interacted')], max_length=20),
        ),
    ]
