# Generated by Django 6.0.2 on 2026-02-07 00:50

from django.db import migrations


def migrate_completed_to_done(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task.objects.filter(is_completed=True).update(status='done')


def reverse_migrate(apps, schema_editor):
    # No reverse needed - status can stay as is
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_task_status_subtask'),
    ]

    operations = [
        migrations.RunPython(migrate_completed_to_done, reverse_migrate),
    ]
