# Generated by Django 6.0.2 on 2026-02-08 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocking', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.PositiveIntegerField(default=0, help_text='Agile estimation points'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Feature', 'Feature'), ('Bug', 'Bug'), ('Chore', 'Chore'), ('Improvement', 'Improvement'), ('Story', 'Story')], default='Feature', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='time_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours spent', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10),
        ),
    ]
